name: jlq_swift
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - ncurses=6.4
  - openssl=3.0.16
  - pip=25.0
  - python=3.10.16
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.45.1
  - xz=5.6.4
  - zlib=1.2.13
  - pip:
      - absl-py==2.2.1
      - accelerate==1.6.0
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.11.14
      - aiosignal==1.3.2
      - airportsdata==20250224
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - altair==5.5.0
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.13.2
      - anyio==4.9.0
      - astor==0.8.1
      - async-timeout==5.0.1
      - attrdict==2.0.1
      - attrs==25.3.0
      - av==14.3.0
      - beautifulsoup4==4.13.3
      - binpacking==1.5.2
      - bitsandbytes==0.45.5
      - blake3==1.0.4
      - blinker==1.9.0
      - cachetools==5.5.2
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - cloudpickle==3.1.1
      - colorama==0.4.6
      - compressed-tensors==0.9.3
      - contourpy==1.3.1
      - cpm-kernels==1.0.11
      - crcmod==1.7
      - cryptography==44.0.3
      - cupy-cuda12x==13.4.1
      - cycler==0.12.1
      - dacite==1.9.2
      - datasets==3.2.0
      - decord==0.6.0
      - deepspeed==0.16.5
      - deprecated==1.2.18
      - depyf==0.18.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distro==1.9.0
      - dnspython==2.7.0
      - docker-pycreds==0.4.0
      - einops==0.6.1
      - einops-exts==0.0.4
      - email-validator==2.2.0
      - et-xmlfile==2.0.0
      - exceptiongroup==1.2.2
      - fastapi==0.115.12
      - fastapi-cli==0.0.7
      - fastrlock==0.8.3
      - ffmpy==0.5.0
      - filelock==3.18.0
      - flash-attn==2.3.6
      - fonttools==4.56.0
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - future==1.0.0
      - gdown==5.2.0
      - gguf==0.16.3
      - gitdb==4.0.12
      - gitpython==3.1.44
      - googleapis-common-protos==1.70.0
      - gradio==5.29.0
      - gradio-client==1.10.0
      - groovy==0.1.2
      - grpcio==1.71.0
      - h11==0.16.0
      - hf-xet==1.1.0
      - hjson==3.1.0
      - httpcore==1.0.9
      - httptools==0.6.4
      - httpx==0.28.1
      - huggingface-hub==0.30.2
      - idna==3.10
      - imageio==2.37.0
      - importlib-metadata==8.0.0
      - interegular==0.3.3
      - jieba==0.42.1
      - jinja2==3.1.6
      - jiter==0.9.0
      - jmespath==0.10.0
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - kiwisolver==1.4.8
      - lark==1.2.2
      - latex2mathml==3.77.0
      - latex2sympy2-extended==1.10.1
      - linkify-it-py==2.0.3
      - llguidance==0.7.19
      - llvmlite==0.44.0
      - lm-format-enforcer==0.10.11
      - markdown==3.7
      - markdown-it-py==2.2.0
      - markdown2==2.5.3
      - markupsafe==3.0.2
      - math-verify==0.7.0
      - matplotlib==3.10.1
      - mdit-py-plugins==0.3.3
      - mdurl==0.1.2
      - mistral-common==1.5.4
      - mmcls==0.25.0
      - mmcv==2.2.0
      - mmcv-full==1.6.2
      - mmengine==0.10.7
      - mmsegmentation==0.30.0
      - model-index==0.1.11
      - modelscope==1.25.0
      - mpmath==1.3.0
      - ms-swift==3.4.0
      - msgpack==1.1.0
      - msgspec==0.19.0
      - multidict==6.2.0
      - multiprocess==0.70.16
      - narwhals==1.32.0
      - nest-asyncio==1.6.0
      - networkx==3.4.2
      - ninja==1.11.1.4
      - nltk==3.9.1
      - numba==0.61.2
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-cusparselt-cu12==0.6.2
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - openai==1.77.0
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - opendatalab==0.0.10
      - openmim==0.3.9
      - openpyxl==3.1.5
      - opentelemetry-api==1.26.0
      - opentelemetry-exporter-otlp==1.26.0
      - opentelemetry-exporter-otlp-proto-common==1.26.0
      - opentelemetry-exporter-otlp-proto-grpc==1.26.0
      - opentelemetry-exporter-otlp-proto-http==1.26.0
      - opentelemetry-proto==1.26.0
      - opentelemetry-sdk==1.26.0
      - opentelemetry-semantic-conventions==0.47b0
      - opentelemetry-semantic-conventions-ai==0.4.6
      - openxlab==0.0.11
      - ordered-set==4.1.0
      - orjson==3.10.16
      - oss2==2.19.1
      - outlines==0.1.11
      - outlines-core==0.1.26
      - packaging==24.2
      - pandas==2.2.3
      - partial-json-parser==0.2.1.1.post5
      - peft==0.15.2
      - pillow==11.1.0
      - platformdirs==4.3.7
      - prettytable==3.16.0
      - prometheus-client==0.21.1
      - prometheus-fastapi-instrumentator==7.1.0
      - propcache==0.3.1
      - protobuf==4.25.7
      - psutil==7.0.0
      - py-cpuinfo==9.0.0
      - pyarrow==19.0.1
      - pycocoevalcap==1.2
      - pycocotools==2.0.8
      - pycountry==24.6.1
      - pycparser==2.22
      - pycryptodome==3.22.0
      - pydantic==2.11.1
      - pydantic-core==2.33.0
      - pydeck==0.9.1
      - pydub==0.25.1
      - pygments==2.19.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.1.0
      - python-json-logger==3.3.0
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - pyzmq==26.4.0
      - qwen-vl-utils==0.0.11
      - ray==2.45.0
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - rich==13.9.4
      - rich-toolkit==0.14.5
      - rouge==1.0.1
      - rpds-py==0.24.0
      - ruff==0.11.8
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-learn==1.6.1
      - scipy==1.15.2
      - semantic-version==2.10.0
      - sentencepiece==0.2.0
      - sentry-sdk==2.27.0
      - setproctitle==1.3.6
      - setuptools==69.5.1
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - simplejson==3.20.1
      - six==1.17.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - sortedcontainers==2.4.0
      - soupsieve==2.6
      - starlette==0.46.1
      - streamlit==1.44.0
      - streamlit-image-select==0.6.0
      - svgwrite==1.4.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tenacity==9.0.0
      - tensorboard==2.19.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - termcolor==2.5.0
      - threadpoolctl==3.6.0
      - tiktoken==0.9.0
      - timm==0.9.12
      - tokenizers==0.21.1
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.2
      - torch==2.6.0
      - torchaudio==2.6.0
      - torchvision==0.21.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - transformers==4.51.3
      - transformers-stream-generator==0.0.5
      - triton==3.2.0
      - trl==0.17.0
      - typer==0.15.3
      - typing-extensions==4.13.0
      - typing-inspection==0.4.0
      - tzdata==2025.2
      - uc-micro-py==1.0.3
      - urllib3==2.3.0
      - uvicorn==0.34.0
      - uvloop==0.21.0
      - vllm==0.8.5.post1
      - wandb==0.19.10
      - watchdog==6.0.0
      - watchfiles==1.0.5
      - wavedrom==2.0.3.post3
      - wcwidth==0.2.13
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.29.post2
      - xgrammar==0.1.18
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.40.1
      - yarl==1.18.3
      - zipp==3.21.0
      - zstandard==0.23.0
